services:
  audiobook-backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/audiobooks:/app/audiobooks
      - ./backend/static:/app/static
      - /var/run/docker.sock:/var/run/docker.sock  # Acesso ao Docker
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"

  audiobook-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - audiobook-backend
    restart: "no"

volumes:
  uploads:
  audiobooks:
  static:
